name: graphic_example
description: Example and debug app for Graphic.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphic:
    path: ../
  intl: ^0.17.0
  quiver: ^3.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
