name: graphic
description: A grammar of data visualization and Flutter charting library.
version: 2.4.0
homepage: https://github.com/entronad/graphic

topics:
  - chart
  - charts
  - visualization
  - diagram
  - plot

environment:
  sdk: '>=2.13.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  vector_math: ^2.1.0
  path_drawing: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
